#ifndef MAPRENDER_H
#define MAPRENDER_H

#include<d3dx9.h>

//描画するマップチップの個数です
#define RENDERSTAGE1MAPCHIPNUM_HEIGHT 26
#define RENDERSTAGE1MAPCHIPNUM_WIDTH 44

//マップチップのサイズです
#define TIPSIZE 32.0f

enum MapKind {  
	NOTHING, 
	FLOOR,
	WALL,
	BLOCK,
	CEILING,//天井 
	UPNEEDLE,
	LEFTNEEDLE,
	RIGHTNEEDLE,
	DANGEROUS,//危険警告ブロック
	TRANSPARENTBLOCK,
	BOSS_SHUTTER, 
	SHUTTER_1, 
	SHUTTER_2, 
	SHUTTER_3, 
	SHUTTER_A, 
	SHUTTER_B, 
	SHUTTER_C,
	SWITCH_1,
	SWITCH_2,
	SWITCH_3,
	HOLE,
	WALKINGENEMY_1,//地上敵
	WALKINGENEMY_2,
	WALKINGENEMY_3,
	WALKINGENEMY_4,
	WALKINGENEMY_5,
	WALKINGENEMY_HAS_KEY_1,
	WALKINGENEMY_HAS_KEY_2,
	WALKINGENEMY_HAS_KEY_3,
	FIXEDBATTERY1,//固定砲台
	DUMMY,//予備
	FLYINGENEMY1,//空中敵
	FLYINGENEMY2,
	FLYINGENEMY3,
	FLYINGENEMY4,//体力強化型
	FLYINGENEMY5,
	FLYINGENEMY_HAS_KEY1,
	FLYINGENEMY_HAS_KEY2,
	FLYINGENEMY_HAS_KEY3,
	FIXEDBATTERY2,
	STARTLOCATION,//たけるスタート地点
	BOSS_STAGE1,
	BOSS_STAGE2,
	BOSS_STAGE3,
	BOSS_STAGE4,
	DUMMY2,//予備隠し用
	RESPAWN_POINT1,//リスポーン地点
	RESPAWN_POINT2,
	FLOOR2 = 61,
	WALL2,
	BLOCK2,
	CEILING2,//天井 
	FLOOR3,
	WALL3,
	BLOCK3,
	CEILING3,//天井 
	FLOOR4,
	WALL4,
	BLOCK4,
	CEILING4,//天井 
	WALKINGENEMY_6,//体力強化型
	WALKINGENEMY_HAS_KEY_4 = 81,
	WALKINGENEMY_HAS_KEY_5,
	WALKINGENEMY_HAS_KEY_6,
	SHUTTER_4 = 91,
	SHUTTER_5,

};

void MapRender();

#endif
