#ifndef PLAYERRENDER
#define PLAYERRENDER

#define PLAYERSIZEPNGWIDTH 90.0f
#define PLAYERSIZEPNGHEIGHT 130.0f
#define PLAYERSIZEWIDTH 52.0f
#define PLAYERSIZEHEIGHT 118.0f

enum PLAYERANIM {
	STANDBY1,
	STANDBY2,
	JUMP1 = 10,
	JUMP2,
	JUMP3,
	JUMP4,
	JUMP5,
	JUMP6,
	JUMP7,
	RUN1 = 20,
	RUN2,
	RUN3,
	RUN4,
	RUN5,
	RUN6,
	RUN7,
	RUN8,
	STANDDOWNSWING1 = 30,
	STANDDOWNSWING2,
	STANDDOWNSWING3,
	STANDDOWNSWING4,
	STANDDOWNSWING5,
	STANDDOWNSWING6,
	STANDUPSWING1 = 40,
	STANDUPSWING2,
	STANDUPSWING3,
	STANDUPSWING4,
	STANDUPSWING5,
	STANDUPSWING6,
	JUMPDOWNSWING1 = 50,
	JUMPDOWNSWING2,
	JUMPDOWNSWING3,
	JUMPDOWNSWING4,
	JUMPDOWNSWING5,
	JUMPDOWNSWING6,
	JUMPUPSWING1 = 60,
	JUMPUPSWING2,
	JUMPUPSWING3,
	JUMPUPSWING4,
	JUMPUPSWING5,
	JUMPUPSWING6,
	RUNDOWNSWING1 = 90,
	RUNDOWNSWING2,
	RUNDOWNSWING3,
	RUNDOWNSWING4,
	RUNDOWNSWING5,
	RUNDOWNSWING6,
	RUNUPSWING1 = 100,
	RUNUPSWING2,
	RUNUPSWING3,
	RUNUPSWING4,
	RUNUPSWING5,
	RUNUPSWING6,
};

void PlayerRender();

#endif
